title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://mhaslam.github.com/long-haul
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mhaslam
   twitter: malcolmhasalm
   facebook: pibelibre
   email: bmhaslam@gmail.com

